# Generated by Django 4.0.3 on 2022-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20220322_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='credit_fee',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fee',
            name='debit_fee',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
